services:
  - type: web
    name: cricket-voting-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
